sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t kim206gh/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true kim206gh/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test successd"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-us-east-2-064875866284
  bucket_path: docker-react-app
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key : $AWS_SECRET_ACCESS_KEY
